FROM scalingo/scalingo-18:latest

ENV DEBIAN_FRONTEND noninteractive

RUN \
  apt-get upgrade -y && \
  apt-get update -y && \
  apt-get install -y uuid-dev gperf

ADD ./harfbuzz.tar.bz2 /tmp
ADD ./freetype.tar.bz2 /tmp
ADD ./pixman.tar.gz /tmp
ADD ./giflib.tar.bz2 /tmp
ADD ./fontconfig.tar.bz2 /tmp
ADD ./cairo.tar.xz /tmp
ADD ./pango.tar.xz /tmp

RUN \
  cd /tmp/harfbuzz-* && \
  ./configure --prefix=/app/vendor/harfbuzz && \
  make install

ENV PKG_CONFIG_PATH /app/vendor/harfbuzz/lib/pkgconfig

RUN \
  cd /tmp/freetype-* && \
  ./configure --prefix=/app/vendor/freetype && \
  make && \
  make install

ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:/app/vendor/freetype/lib/pkgconfig

RUN \
  cd /tmp/pixman-* && \
  ./configure --prefix=/app/vendor/pixman && \
  make install

ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:/app/vendor/pixman/lib/pkgconfig

RUN \
  cd /tmp/giflib-* && \
  ./configure --prefix=/app/vendor/giflib && \
  make install-exec install-data

ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:/app/vendor/giflib/lib/pkgconfig

RUN \
  cd /tmp/fontconfig-* && \
  ./configure --prefix=/app/vendor/fontconfig && \
  make install

ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:/app/vendor/fontconfig/lib/pkgconfig

RUN \
  cd /tmp/cairo-* && \
  ./configure --prefix=/app/vendor/cairo && \
  make install

ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:/app/vendor/cairo/lib/pkgconfig

RUN \
  cd /tmp/pango-* && \
  ./configure --prefix=/app/vendor/pango && \
  make install

RUN \
  cd /app/vendor/pixman && \
  tar zcf /tmp/pixman-scalingo.tar.gz . && \
  cd /app/vendor/freetype && \
  tar zcf /tmp/freetype-scalingo.tar.gz . && \
  cd /app/vendor/giflib && \
  tar zcf /tmp/giflib-scalingo.tar.gz . && \
  cd /app/vendor/fontconfig && \
  tar zcf /tmp/fontconfig-scalingo.tar.gz . && \
  cd /app/vendor/cairo && \
  tar zcf /tmp/cairo-scalingo.tar.gz . && \
  cd /app/vendor/harfbuzz && \
  tar zcf /tmp/harfbuzz-scalingo.tar.gz . && \
  cd /app/vendor/pango && \
  tar zcf /tmp/pango-scalingo.tar.gz .
